name: setifikasi_bnsp
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  select_form_field: ^2.2.0
  cupertino_icons: ^1.0.0
  connectivity_plus: ^0.9.0-nullsafety.0


  image_picker: any
  tabler_icons: ^2.5.0+1
  flutter_bloc: ^8.1.2
  provider: ^6.0.5
  flutter_svg: ^0.22.0-nullsafety.3
  curved_navigation_bar: ^1.0.3

  get: 4.6.5
  quickalert: 1.0.1
  introduction_screen: ^3.1.8
  path: ^1.8.2
  path_provider: ^2.0.11
  flutter:
    sdk: flutter
  go_router: ^11.0.0
  sqflite: ^2.3.0
  syncfusion_flutter_charts: ^23.1.36
  get_storage: ^2.1.1
  intl: ^0.18.1
  flutter_easyloading: ^3.0.5
  lecle_downloads_path_provider: ^0.0.2+8

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  test: ^1.24.1

flutter:
  assets:
    - assets/images/
    - assets/images/onboard/
    - assets/images/splashscreen/
    - assets/icons/
  uses-material-design: true